### ISSUE TITLE
Crash when converting model containing 8-bit sparse accessor indices

### ISSUE THREAD

**Issue by kourion11** [warrenm/GLTFKit2#52] opened 2024-01-19 08:49 UTC
Hi, it gives an error and crashes the application when using this model
Error:
`Assertion failed: (accessor.sparse.indexComponentType == GLTFComponentTypeUnsignedShort || accessor.sparse.indexComponentType == GLTFComponentTypeUnsignedInt), function GLTFSCNPackedDataForAccessor, file GLTFSceneKit.m, line 321.`
Model:
[avatar_1705565985793.glb.zip](https://github.com/warrenm/GLTFKit2/files/13986617/avatar_1705565985793.glb.zip)

**Comment by warrenm** [comment] 2024-01-19 14:24
This sounds like a duplicate of #49. Make sure you've updated to at least 1bbc10e or version [0.5.7](https://github.com/warrenm/GLTFKit2/releases/tag/0.5.7).

**Comment by kourion11** [comment] 2024-01-19 15:00
Sorry for a duplicate!
Thank you!

**Comment by warrenm** [comment] 2024-01-19 15:42
Thanks for confirming!

**Closed as completed by warrenm** 2024-01-19 15:42 UTC

**Comment by kourion11** [comment] 2024-01-21 20:36
Unfortunately in version 0.5.7 the same thing happens( 
Can you please check this model for me?
